[package]
name = "ultralogi-rs"
version = "0.1.0"
license = "AGPL-3.0"
edition = "2024"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
duckdb = { version = "1.4.3", features = ["bundled"] }
# Must match duckdb's arrow version (56.x)
arrow = { version = "56", default-features = false, features = ["ipc"] }
once_cell = "1"
anyhow = "1.0"
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
